name: "Build and test"
description: "Build container and run tests"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
      uses: actions/setup-python@v1
      - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install docker.io make
        sudo make build
      
      - name: Run tests
      run: |
        sudo make test