name: "Build and test"
description: "Build container and run tests"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: |
        sudo apt update
        sudo apt install docker.io make
        sudo make build
      - run: |
        sudo make test